### ISSUE TITLE
Possible Database Race Condition

### ISSUE THREAD

**Issue by rokaskasperavicius** [DevOps-Ben11/minitwit#36]
![Screenshot 2024-04-02 at 14 07 17](https://github.com/DevOps-Ben11/minitwit/assets/22415563/1622cfca-0d51-4e66-a986-658ce4a5d974)

This was noticed after running e2e tests in parallel.

**Comment by hrallil** [comment]
We should just add the Unique keyword on the PSQL database, that would remove the race condition.
