### ISSUE TITLE
Database is not synced

### ISSUE THREAD

**Issue by hrallil** [DevOps-Ben11/minitwit#4]
When the docker image is created on the droplet through the vagrant file, the databse used is ./tmp/minitwit.db, however when changes to the database are made, the changes only happen to a local database in the image. 

**The ./tmp/minitwit.db is not updated** 

We need to synchronize the updating of the data base in the docker and the database outside of the docker, or we should make a connection to the image which makes the image interact exclusively with an external database. 

This also becomes a problem when redeploying. If we take down the droplet, or recreate the docker-image, the stored data in the image is lost.

**Comment by rokaskasperavicius** [comment]
Has been fixed on [macrowit](https://github.com/DevOps-Ben11/minitwit/tree/macrowit) branch.

The new setup will only push `/scripts` and `/tmp` to VPS. The `Dockerfile` only builds the site based on the `/backend` and `/web` folders. The /tmp is mounted as a volume on the VPS. Therefore, the database on production will be always isolated from development changes and will sync to docker container.
