### ISSUE TITLE
Response time is >0.3 seconds (~2 seconds)

### ISSUE THREAD

**Issue by hrallil** [DevOps-Ben11/minitwit#9]
### What is the problem 
When testing the sim API, we noticed that all the requests timed out. After re-running the API with a higher timeout boundary (5 seconds) we declared that the API works, how ever with a performance discrepancy. 

To test the API manually we sent a request through Postman, and found that the average registration took about 2 seconds.

### What we suspect the reason is
We suspect that the database is the bottleneck, and we want to **migrate from SQLite3 to something faster**.

**Comment by rokaskasperavicius** [comment]
Fixed the issue with #10
